language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text